spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_pms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  level:
    cn.chen.csmall: trace

server:
  port: 6080

csmall:
  jwt:
    secret-key: kU4jrFA3iuI5jn25u743kfDs7a8pFEwS54hm
#      duration-in-minute: 14400