spring:
  datasource:
    url: jdbc:mysql://localhost:3306:/mall_pms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

logging:
  level:
    cn.chen.csmall = info



#spring.datasource.username=csmall-admin
#spring.datasource.password=P@ssw0rd2211